#!/usr/bin/python
import json
import time

with open('/var/run/dump1090-fa/aircraft.json', 'r') as f:
     data = json.load(f)


planes = data["aircraft"]

t = int(time.time())
d = t % 86400

print(len(planes))

count = 0

for plane in planes:
	noticed = plane["seen"]
	if noticed < 58:
		count = count + 1


print t,d,count
